apiVersion: apps/v1
kind: Deployment
metadata:
  name: deaddrop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deaddrop
  template:
    metadata:
      labels:
        name: deaddrop
    spec:
      containers:
      - name: deaddrop
        image: ghcr.io/totegamma/deaddrop:v0.0.0
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: deaddrop
spec:
  selector:
    name: deaddrop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
